### ISSUE TITLE
Wrong database in case of HG multi databases

### ISSUE THREAD

**Issue by Xara** [djphil/osregister#2]
What is needed to been set when configuring component is ROBUST database not and not SIM one...

**Comment by djphil** [comment]
**osregister** does not use the simulator database tables, except in Standalone mode.
In Grid mode, it's only the Robust database tables that are needed and Hypergrid does not change that.
So at this point, unless I'm mistaken, I do not see any problem but maybe you can clarify ?

**Comment by Xara** [comment]
Is a mistake in documentation, how to install, not in code, if you follow what you tell, you hit simulator database not, grid one, then no regions, no users tables, but again, is only error in how to in Joomla help.

**Comment by djphil** [comment]
**osregister** is not related to **Joomla**, why are you talking about **Joomla** here ?
The **osregister** documentation is available [here](https://github.com/djphil/osregister/wiki#install) ("**Install**" section is currently "**TODO ...**").
... or I do not understand what you are explaining (in this case, can you clarify ?).
