### ISSUE TITLE
avatar en fantome

### ISSUE THREAD

**Issue by meme0623** [djphil/osregister#3]
Bonjour Djphil ,
Peut tu m'aider avec osregister ,j'ai bien creer les avats ,le dossier ,mais lorsqu'ils arrivent ils ne portent rien . 

De plus si tu pouvait me reexpliquer pour changer le theme a slate .

Merçi d'avance

Amitiés 
Vlad

**Comment by djphil** [comment]
Bonjour Vlad,

Si il ne porte vraiment rien ça c'est embébtant ... 
Il faudrait vérifier étape par étape si tu as bien procédé. Ensuite, si nécessaire, je vérifierai le code.
Slate est un "extra" ne faisant actuellement pas partie du module osregister.
Je te propose de regarder tous ça ensemble sur ta grille ou sur IRC si ça te convient.

Bien à toi.
djphil

**Comment by djphil** [comment]
Fixed in c5fa23ec8f873e111bcdb1a5ed30b1c6573047d9
Thank's for reporting.

**Comment by meme0623** [comment]
Merçi , 
Cela m'aide vraiment  énormément
Vlad
